---

- name:    Add APT key
  apt_key: url="hkp://keyserver.ubuntu.com:80" id="EA312927"

- name:    Create a list file for MongoDB.
  command: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: Install MongoDB
  apt:  name=mongodb-org state=present update_cache=yes

- name:     configure mongodb
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  tags:     mongodb

- name:    run mongodb
  service: name=mongod state=started enabled=yes
  tags:    mongodb